spring:
  application:
    name: hello-service
  profiles:
    active: dev
  thymeleaf:
    encoding: utf-8
    content-type: text/html
    mode: LEGACYHTML5
    cache: false
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:orcl
    password: 123456
    username: demo
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8080
logging:
  level: info
management:
  security:
    enabled: false